library(dplyr)
library(purrr)
library(tibble)
library(stringr)
library(ggplot2)
library(magrittr)
library(scales)
library(shiny)
library(ggiraph)

source("R/game.R")
source("R/ai.R")
source("R/ui.R")
source("R/server.R")

shinyApp(ui, server)
